before_script:
  - sudo apt-get update -qq
  - sudo apt-get install wget
language: python
python:
  - "2.7"
# command to install dependencies
install:
  - cd ..
  - wget https://www.renpy.org/dl/6.99.14.24.2/renpy-6.99.14.24.2-sdk.tar.bz2
  - tar xf renpy-6.99.14.2-sdk.tar.bz2
  - rm renpy-6.99.14.2-sdk.tar.bz2
  - mv renpy-6.99.14.2-sdk renpy
  - cd renpy
# command to run tests
script: ./renpy.sh "../BarkPack/" lint && ./renpy.sh launcher distribute "../BarkPack/"